### ISSUE TITLE
The naga .jar is distributed as an AOT-compiled lib

### ISSUE THREAD

**Issue by vemv** [threatgrid/naga#133]
Hi!

The distributed naga artifact is AOT-compiled:

![image](https://user-images.githubusercontent.com/1162994/107843931-a3e0ab00-6dcf-11eb-94cc-62809b5a5ce6.png)

This is known as a source of issues ([ref](https://github.com/camsaul/methodical/issues/40#issuecomment-775446224)) and would appreciate if newer releases were source-only.

Thanks - V

**Comment by quoll** [comment]
The problem referenced is not something that will affect Naga. But there is no problem making this change, so I'll ensure that it's in the next version.

The referenced concern is due to shipping with precompiled external dependencies. Outside of the Clojure ecosystem, Naga has very little in the way of external dependencies (it depends on Asami and Zuko, both of which are being developed in conjunction with Naga, and with few external dependencies themselves). If there are issues in the Clojure ecosystem, then there would be problems even if they weren't precompiled.

The only exceptions are in the development environment (which does not affect deployment), and with a dependency on Datomic/postgres. The latter will only show up if Naga is used with those modules enabled. However, Datomic is precompiled anyway, so that is out of our control.

**Comment by quoll** [comment]
Update to Naga 0.3.11, as this does not have AOT compiled code.
